Feature shopping cart
MinoDentori/online-book-store pull request #11
Opened 2024-01-02 21:31 UTC by MinoDentori

Added first version of shopping cart feature implementation.

2024-01-03 09:07 UTC, AgroFix approved these changes

2024-01-03 09:07 UTC, AgroFix commented on src/main/java/mate/academy/onlinebookstore/model/CartItem.java
> +@Where(clause = "is_deleted = false")
```suggestion
@SQLRestriction("is_deleted=false")
```
@Where is deprecated

2024-01-03 09:07 UTC, AgroFix commented on src/main/resources/db/changelog/changes/10-create-shopping-cart-table.yaml
> +                    nullable: false
when column is primary key constraint nullable is redundant, because primary key is unique + not null.

2024-01-03 09:07 UTC, AgroFix commented on src/main/java/mate/academy/onlinebookstore/dto/cart/item/AddToCartRequestDto.java
> +    private int quantity;
I think we should also add @Positive here

2024-01-03 13:29 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +            @RequestBody AddToCartRequestDto requestDto,
```suggestion
            @RequestBody @Valid AddToCartRequestDto requestDto,
```

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +    @GetMapping()
```suggestion
    @GetMapping
```

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/dto/cart/item/UpdateCartItemDto.java
> +    @Positive
From the Positive annotation documentation:
```
...null elements are considered valid.
```

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/model/CartItem.java
> +    @ManyToOne
Please avoid EAGER relations.

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/model/CartItem.java
> +    @ManyToOne
Please avoid EAGER relations.

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/model/ShoppingCart.java
> +    @OneToOne
Please avoid EAGER relations.

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/service/cart/ShoppingCartService.java
> +    ShoppingCartDto updateItem(Long userId, Long id, UpdateCartItemDto requestDto);
In the context of ShoppingCartService it's not obvious which `id` it is, so be more specific.
```suggestion
    ShoppingCartDto updateItem(Long userId, Long cartItemId, UpdateCartItemDto requestDto);
```

2024-01-03 13:29 UTC, vovasalyha commented on src/main/java/mate/academy/onlinebookstore/service/cart/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-01-04 08:42 UTC, d1sam approved these changes
Well done!

2024-01-05 06:12 UTC, merged