Feature book category testing
MinoDentori/online-book-store pull request #14
Opened 2024-01-09 07:34 UTC by MinoDentori

Added tests for Book Entity on the all layers.

2024-01-10 08:53 UTC, BolsunovaNataliia approved these changes

2024-01-10 08:53 UTC, BolsunovaNataliia commented on pom.xml
>          <maven.checkstyle.plugin.configLocation>checkstyle.xml</maven.checkstyle.plugin.configLocation>
Super job! I haven't any notes!

2024-01-10 09:25 UTC, yevheniisynytsia requested changes
Well done! Some comments to improve code style left

2024-01-10 09:25 UTC, yevheniisynytsia commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> -    @ISBN
seems like you don't have validation for isbn in your dto

2024-01-10 09:25 UTC, yevheniisynytsia commented on src/test/java/mate/academy/onlinebookstore/repository/book/BookRepositoryTest.java
> +        Assertions.assertNotNull(actual);
```suggestion

        Assertions.assertNotNull(actual);
```

2024-01-10 09:25 UTC, yevheniisynytsia commented on src/test/java/mate/academy/onlinebookstore/service/book/impl/BookServiceImplTest.java
> +    private BookServiceImpl bookService;
place this under your mocks

2024-01-10 09:25 UTC, yevheniisynytsia commented on src/test/java/mate/academy/onlinebookstore/service/book/impl/BookServiceImplTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual);
exclude id

2024-01-10 09:25 UTC, yevheniisynytsia commented on src/test/java/mate/academy/onlinebookstore/service/book/impl/BookServiceImplTest.java
> +        Mockito.when(bookMapper.toDto(book)).thenReturn(bookDto);
add spaces between blocks - this boosts readability

2024-01-10 09:55 UTC, MinoDentori commented on src/test/java/mate/academy/onlinebookstore/service/book/impl/BookServiceImplTest.java
> +        Mockito.when(bookMapper.toDto(book)).thenReturn(bookDto);
fixed, thx

2024-01-10 09:55 UTC, MinoDentori commented on src/test/java/mate/academy/onlinebookstore/service/book/impl/BookServiceImplTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual);
fixed

2024-01-10 09:55 UTC, MinoDentori commented on src/test/java/mate/academy/onlinebookstore/service/book/impl/BookServiceImplTest.java
> +    private BookServiceImpl bookService;
fixed

2024-01-10 09:55 UTC, MinoDentori commented on src/test/java/mate/academy/onlinebookstore/repository/book/BookRepositoryTest.java
> +        Assertions.assertNotNull(actual);
fixed

2024-01-10 09:57 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> -    @ISBN
Returned annotation, replaced it before in case not to overwhelm testing flow. Changed ISBN test data from random to true valid ISBN. works for now.

2024-01-11 07:41 UTC, d1sam approved these changes
well done!

2024-01-11 07:41 UTC, d1sam commented on src/test/resources/database/book/delete-book.sql
> +DELETE FROM book
```suggestion
DELETE FROM book

```

2024-01-11 07:41 UTC, d1sam commented on src/test/resources/database/book/insert-into-book.sql
> +INSERT INTO book (id, title, author, isbn, price, description) VALUES (1, 'The Buried Giant', 'Kazuo Ishiguro', '9781408711705', 434.00, 'The Buried Giant is a fantasy novel')
```suggestion
INSERT INTO book (id, title, author, isbn, price, description) VALUES (1, 'The Buried Giant', 'Kazuo Ishiguro', '9781408711705', 434.00, 'The Buried Giant is a fantasy novel')

```

2024-01-11 07:41 UTC, d1sam commented on src/test/resources/database/category/delete-book-category.sql
> +DELETE FROM book_category
```suggestion
DELETE FROM book_category

```

2024-01-11 07:41 UTC, d1sam commented on src/test/resources/database/category/delete-category.sql
> +DELETE FROM category
```suggestion
DELETE FROM category

```

2024-01-11 07:41 UTC, d1sam commented on src/test/resources/database/category/insert-into-book-category.sql
> +INSERT INTO book_category (book_id, category_id) VALUES (1, 1)
```suggestion
INSERT INTO book_category (book_id, category_id) VALUES (1, 1)

```

2024-01-11 07:41 UTC, d1sam commented on src/test/resources/database/category/insert-into-category.sql
> +INSERT INTO category (id, name, description) VALUES (1, 'Fantasy', 'Fantasy category')
```suggestion
INSERT INTO category (id, name, description) VALUES (1, 'Fantasy', 'Fantasy category')

```

2024-01-11 19:58 UTC, MinoDentori commented
Fixed all empty lines problems

2024-01-13 08:25 UTC, merged