Added description to README.md file
MinoDentori/online-book-store pull request #15
Opened 2024-01-11 07:20 UTC by MinoDentori

1. Please provide feedback to the parts, of the text, that don't look like human written, cause I used GPT a lot.
2. Need to complete my Postman collection, before inserting it into this file.

2024-01-11 09:04 UTC, d1sam requested changes
Good job, but there are some improvements should be done!

2024-01-11 09:04 UTC, d1sam commented on README.md
> +
what about docker-compose? also please provide maven commands.

2024-01-11 09:04 UTC, d1sam commented on README.md
> +The journey of creating Bookstore Pro wasn't without its challenges:
please rewrite this section without GPT and describe deeper challenges, that you overcomed.

2024-01-11 09:04 UTC, d1sam commented on README.md
please also add Possible improvements section.

2024-01-11 18:36 UTC, MinoDentori commented on README.md
fixed

2024-01-15 10:13 UTC, d1sam approved these changes
well done!

2024-01-16 20:08 UTC, merged