Added implementation of Spring Jpa Task
MinoDentori/online-book-store pull request #3
Opened 2023-12-08 13:59 UTC by MinoDentori

1. Configured liquibase, created changelog master, and created yaml file for the "book" table creation.
2. Updated entity to implement the "soft-delete" concept.
3. Added new endpoints: updateBookByid, and deleteBookById to controller and service layer implementations for them.
4. Testes the app via Postman.

2023-12-08 16:27 UTC, Andriy-Hrynevetskyi approved these changes
GJ!

2023-12-11 10:04 UTC, d1sam requested changes
Well done, but please be careful with exception messages :)

2023-12-11 10:04 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/service/impl/BookServiceImpl.java
> +                new EntityNotFoundException("Can't get employee from DB by id:" + id));
```suggestion
                new EntityNotFoundException("Can't get book from DB by id:" + id));
```

2023-12-11 10:14 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/service/impl/BookServiceImpl.java
> +                new EntityNotFoundException("Can't get employee from DB by id:" + id));
my bad. fixed all

2023-12-11 10:19 UTC, d1sam approved these changes
Well done!

2023-12-11 12:52 UTC, merged