Added impementation for the Criteria Query in Spring Boot task.
MinoDentori/online-book-store pull request #4
Opened 2023-12-08 20:10 UTC by MinoDentori

1. Added Search endpoint to the BookController class.
2. Added service layer implementation for the new endpoint.
3. Created SpecificationBulder and implementation class.
4. Created SpecificatoinProvider interface and implementations: AuthorSpecificationProvider, TitleSpecificationProvider, IsbnSpecificationProvider for filtration by corresponding Book field.
5. Created SpecificationProviderManager for better control of getting specific SpecificationProvider implementation.
6. Tested via Postman.

2023-12-12 10:23 UTC, d1sam requested changes
Well done, but please avoid String literals

2023-12-12 10:23 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/AuthorSpecificationProvider.java
> +        return "author";
Please make `"author"` as constant

2023-12-12 10:23 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/AuthorSpecificationProvider.java
> +                root.get("author").in(Arrays.stream(params).toArray());
Please make `"author"` as constant

2023-12-12 10:23 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/IsbnSpecificationProvider.java
> +        return "isbn";
Please make `"isbn"` as constant

2023-12-12 10:23 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/IsbnSpecificationProvider.java
> +                root.get("isbn").in(Arrays.stream(params).toArray());
Please make `"isbn"` as constant

2023-12-12 10:23 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/TitleSpecificationProvider.java
> +        return "title";
Please make `"title"` as constant

2023-12-12 10:23 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/TitleSpecificationProvider.java
> +                root.get("title").in(Arrays.stream(params).toArray());
Please make `"title"` as constant

2023-12-12 11:50 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/AuthorSpecificationProvider.java
> +        return "author";
fixed

2023-12-12 11:50 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/IsbnSpecificationProvider.java
> +        return "isbn";
fixed

2023-12-12 11:50 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/AuthorSpecificationProvider.java
> +                root.get("author").in(Arrays.stream(params).toArray());
fixed

2023-12-12 11:50 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/TitleSpecificationProvider.java
> +        return "title";
fixed

2023-12-12 11:51 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/IsbnSpecificationProvider.java
> +                root.get("isbn").in(Arrays.stream(params).toArray());
fixed

2023-12-12 11:51 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/repository/book/spec/TitleSpecificationProvider.java
> +                root.get("title").in(Arrays.stream(params).toArray());
fixed

2023-12-13 07:13 UTC, kshuryhin approved these changes
Looks good!

2023-12-13 07:40 UTC, merged