Added implementation for the Global Exception Handler feature
MinoDentori/online-book-store pull request #5
Opened 2023-12-11 15:16 UTC by MinoDentori

1. Added hibernate-validator dependency.
2. Added validator annotations to the CreateRequestBookDto class
3. Added @Validate annotation to the save, and update methods in the Controller class.
4. Created CustomGlobalHandlerException class to handle exceptions thrown by the validator.

2023-12-12 10:00 UTC, dima-semeniuk approved these changes
Looks good, but think about adding to CustomGlobalExcHandler method to handle EntityNotFoundException

2023-12-12 10:39 UTC, d1sam requested changes
Good job, but some changes should be done, please look at my comments.

2023-12-12 10:39 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Min(0)
```suggestion
    @Positive
```

2023-12-12 10:39 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/dto/CreateBookRequestDto.java
please provide your custom informative messages :)

2023-12-12 10:39 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/exception/CustomGlobalExceptionHandler.java
you should also write `@ExceptionHandler` for your `EntityNotFoundException`

2023-12-12 10:39 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
try to avoid String literals

2023-12-17 15:48 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
fixed

2023-12-17 15:48 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Min(0)
fixed

2023-12-17 18:58 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/exception/CustomGlobalExceptionHandler.java
fixed

2023-12-17 19:10 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/dto/CreateBookRequestDto.java
fixed

2023-12-18 08:04 UTC, kshuryhin approved these changes
great job

2023-12-18 08:26 UTC, merged