Added implementation for the Pagination feature, added swager-ui dependencies.
MinoDentori/online-book-store pull request #6
Opened 2023-12-12 11:43 UTC by MinoDentori

1. Added dependencies for the OpenDoc swagger specification.
2. Specified path to API docs in application properties.
3. Change getAll endpoint to accept Paginable objects as a parameter.
4. Added getAll(Paginable paginable) method to the BookService and implementation to the BookServiceImpl.
5. Fixed code style.
6. Tested via Postman.

2023-12-13 10:32 UTC, HovorukhaBohdan requested changes

2023-12-13 10:32 UTC, HovorukhaBohdan commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +    @Operation(summary = "Find book by id")
I think we should provide description for `@Operation`. Like this:
![image](https://github.com/MinoDentori/online-book-store/assets/144166480/c24cd558-c832-4c7a-a22a-598c589f8595)

2023-12-17 15:34 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +    @Operation(summary = "Find book by id")
fixed

2023-12-18 06:42 UTC, kshuryhin requested changes
great job, just one point to consider

2023-12-18 06:42 UTC, kshuryhin commented on src/main/java/mate/academy/onlinebookstore/service/BookService.java
> +    List<BookDto> getAll(Pageable pageable);
just wondering if you need both these methods for fetching, although you're using in the API only pageable one

2023-12-18 07:46 UTC, MinoDentori commented on src/main/java/mate/academy/onlinebookstore/service/BookService.java
> +    List<BookDto> getAll(Pageable pageable);
really, no usages for getAl(), cleared.

2023-12-18 08:04 UTC, kshuryhin approved these changes
looks good

2023-12-18 08:27 UTC, merged