Feature basic authentification security 2
MinoDentori/online-book-store pull request #8
Opened 2023-12-22 07:05 UTC by MinoDentori

Added implementation of the basic authentification, and added roles.

2023-12-22 17:42 UTC, Andriy-Hrynevetskyi approved these changes
LGTM GJ)

2023-12-26 09:14 UTC, d1sam requested changes
Good job, but some changes should be done according to my comment

2023-12-26 09:14 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**", "/error")
where is swagger?

2023-12-26 09:14 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ADMIN') or hasRole('USER')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```

2023-12-26 09:14 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ADMIN') or hasRole('USER')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```

2023-12-26 09:14 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 09:14 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 09:14 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 09:14 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/repository/role/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
```suggestion
@Repository
public interface RoleRepository extends JpaRepository<Role, Long> {
```

2023-12-26 09:14 UTC, d1sam commented on src/main/resources/db/changelog/changes/03-create-role-table.yaml
> +                    nullable: false
please add empty line to the end of file

2023-12-26 09:14 UTC, d1sam commented on src/main/resources/db/changelog/changes/03-create-role-table.yaml
> +                    nullable: false
add unique constraint

2023-12-26 09:14 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-user-role-table.yaml
> +                  type: bigint
please add empty line to the end of file

2023-12-26 09:14 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-user-role-table.yaml
> +                  name: id
you don't need this col

2023-12-26 09:14 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-insert-into-role.yaml
Be sure you have at least one user in DB with role admin

2023-12-27 10:50 UTC, d1sam requested changes
good job, but some changes should be done. and please remove changes from another hw.

2023-12-27 10:50 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**", "/error", "/swagger-ui/**")
```suggestion
                                .requestMatchers("/auth/**", "/error", "/v3/api-docs/**", "/swagger-ui/**")
```

2023-12-27 10:50 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/model/User.java
`UserDetails` from another hw

2023-12-27 10:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
please add empty line to the end of file

2023-12-27 10:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/02-create-user-table.yaml
> +                    nullable: false
please add empty line to the end of file

2023-12-27 10:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/03-create-role-table.yaml
> +                    nullable: false
please add empty line to the end of file

2023-12-27 10:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-insert-roles-into-role-table.yaml
> +                  value: USER
please add empty line to the end of file

2023-12-27 10:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-insert-users-into-user-table.yaml
> +                  value: AdminLastName
please add empty line to the end of file

2023-12-27 10:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/07-insert-users-roles-into-user-role-table.yaml
> +                  value: 1
please add empty line to the end of file

2023-12-27 10:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/07-insert-users-roles-into-user-role-table.yaml
> +                  value: 1
please use `valueComputed` instead of hard-coded values:
```
      preConditions:
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM users WHERE email='admin@example.com'
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM roles WHERE name='ROLE_ADMIN'
      changes:
        - insert:
            tableName: user_role
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email='admin@example.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name='ROLE_ADMIN')
```

2023-12-27 10:50 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore/security/CustomUserDetailService.java
this class from another hw

2023-12-27 11:23 UTC, d1sam approved these changes
Well done!

2023-12-27 14:41 UTC, merged