Implment JWT featurt
MinoDentori/online-book-store pull request #9
Opened 2023-12-25 19:27 UTC by MinoDentori

1. Added required dependencies.
2. Added new beans to the SecurityConfig file.
3. Create a util class to work with the JWT token.
4. Created JWT filter and added it to the FilterChain.
5. Added login endpoint to Authenticate controller.

2023-12-26 13:58 UTC, andrii-hoienko requested changes

2023-12-26 13:58 UTC, andrii-hoienko commented on src/main/java/mate/academy/onlinebookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
Add @Valid annotation to apply validation rules you defined

2023-12-26 13:58 UTC, andrii-hoienko commented on src/main/java/mate/academy/onlinebookstore/util/ConstraintsMessages.java
>      private ConstraintsMessages() {
Are you sure this class should be named ConstraintsMessages maybe names like "MessagesConstants", "ErrorMessagesConstants" etc. will be better.

2023-12-27 11:17 UTC, d1sam approved these changes
Well done!

2023-12-27 14:41 UTC, merged